name: Commit
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm config set engine-strict true
          npm install
        env:
          CI: true
      - name: Run Tests
        run: "npx nyc --reporter=lcov npm run test:unit"
        env:
          CI: true
      - name: Upload Coverage Info
        if: "${{ matrix.node-version }} == 10.x"
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage/lcov.info

