name: Commit
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm config set engine-strict true
          npm install
        env:
          CI: true
      - name: Run Tests
        run: "npx nyc --reporter=clover npm run test:unit"
        env:
          CI: true
      - name: Coveralls
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.github_token }}
      - name: Upload coverage
        if: success() && matrix.node-version == 10.x'
        run: bash <(curl -s https://codecov.io/bash) -v -t $TOKEN -B $BRANCH -C $SHA -f ./coverage/clover.xml
        env:
          TOKEN: "${{ secrets.CODECOV_TOKEN }}"
          BRANCH: "${{ github.ref }}"
          SHA: "${{ github.sha }}"
          SLUG: "${{ github.slug }}"
